export enum Language {
  Arabic,
  English,
}

export enum ColumnName {
  Name = 'Name',
  ArabicName = 'Arabic Name',
  Transliteration = 'Transliteration',
  Isolated = 'Isolated',
  Initial = 'Initial',
  Medial = 'Medial',
  Final = 'Final',
  Pronunciation = 'Pronunciation',
}

export interface Column {
  id: number
  name: ColumnName
  position: number
  language: Language
  show: boolean
}

export const column: { [id: number]: Column } = {
  0: {
    id: 0,
    name: ColumnName.Name,
    position: 0,
    language: Language.English,
    show: true,
  },
  1: {
    id: 1,
    name: ColumnName.ArabicName,
    position: 1,
    language: Language.Arabic,
    show: true,
  },
  2: {
    id: 2,
    name: ColumnName.Transliteration,
    position: 2,
    language: Language.English,
    show: true,
  },
  3: {
    id: 3,
    name: ColumnName.Isolated,
    position: 3,
    language: Language.Arabic,
    show: true,
  },
  4: {
    id: 4,
    name: ColumnName.Initial,
    position: 4,
    language: Language.Arabic,
    show: true,
  },
  5: {
    id: 5,
    name: ColumnName.Medial,
    position: 5,
    language: Language.Arabic,
    show: true,
  },
  6: {
    id: 6,
    name: ColumnName.Final,
    position: 6,
    language: Language.Arabic,
    show: true,
  },
  7: {
    id: 7,
    name: ColumnName.Pronunciation,
    position: 7,
    language: Language.English,
    show: true,
  },
}

export class Letter {
  public readonly [ColumnName.Name]: string
  public readonly [ColumnName.ArabicName]: string
  public readonly [ColumnName.Transliteration]: string
  public readonly [ColumnName.Isolated]: string
  public readonly [ColumnName.Initial]: string
  public readonly [ColumnName.Medial]: string
  public readonly [ColumnName.Final]: string
  public readonly [ColumnName.Pronunciation]: string
}

export const letters: Letter[] = [
  {
    [ColumnName.Name]: 'ʾalif',
    [ColumnName.ArabicName]: 'أَلِف',
    [ColumnName.Transliteration]: `ā (also â)`,
    [ColumnName.Isolated]: 'ﺍ',
    [ColumnName.Initial]: 'ﺍ',
    [ColumnName.Medial]: 'ﺎ',
    [ColumnName.Final]: 'ﺎ',
    [ColumnName.Pronunciation]: 'c{a}r, c{a}t',
  },
  {
    [ColumnName.Name]: 'bāʾ',
    [ColumnName.ArabicName]: 'بَاء',
    [ColumnName.Transliteration]: 'b',
    [ColumnName.Isolated]: 'ب',
    [ColumnName.Initial]: 'بـ',
    [ColumnName.Medial]: 'ـبـ',
    [ColumnName.Final]: 'ـب',
    [ColumnName.Pronunciation]: '{b}arn',
  },
  {
    [ColumnName.Name]: 'tāʾ',
    [ColumnName.ArabicName]: 'تَاء',
    [ColumnName.Transliteration]: 't',
    [ColumnName.Isolated]: 'ت',
    [ColumnName.Initial]: 'تـ',
    [ColumnName.Medial]: 'ـتـ',
    [ColumnName.Final]: 'ـت',
    [ColumnName.Pronunciation]: 's{t}ick',
  },
  {
    [ColumnName.Name]: 'thāʾ',
    [ColumnName.ArabicName]: 'ثَاء',
    [ColumnName.Transliteration]: `th (also ṯ)`,
    [ColumnName.Isolated]: 'ث',
    [ColumnName.Initial]: 'ثـ',
    [ColumnName.Medial]: 'ـثـ',
    [ColumnName.Final]: 'ـث',
    [ColumnName.Pronunciation]: '{th}ink',
  },
  {
    [ColumnName.Name]: 'jīm',
    [ColumnName.ArabicName]: 'جِيم',
    [ColumnName.Transliteration]: `j (also ǧ)`,
    [ColumnName.Isolated]: 'ج',
    [ColumnName.Initial]: 'جـ',
    [ColumnName.Medial]: 'ـجـ',
    [ColumnName.Final]: 'ـج',
    [ColumnName.Pronunciation]: '{g}em',
  },
  {
    [ColumnName.Name]: 'ḥāʾ',
    [ColumnName.ArabicName]: 'حَاء',
    [ColumnName.Transliteration]: `ḥ (also ḩ)`,
    [ColumnName.Isolated]: 'ح',
    [ColumnName.Initial]: 'حـ',
    [ColumnName.Medial]: 'ـحـ',
    [ColumnName.Final]: 'ـح',
    [ColumnName.Pronunciation]: 'guttural h like "{h}eart"',
  },
  {
    [ColumnName.Name]: 'khāʾ',
    [ColumnName.ArabicName]: 'خَاء',
    [ColumnName.Transliteration]: `kh (also ḫ, ḵ, ẖ)`,
    [ColumnName.Isolated]: 'خ',
    [ColumnName.Initial]: 'خـ',
    [ColumnName.Medial]: 'ـخـ',
    [ColumnName.Final]: 'ـخ',
    [ColumnName.Pronunciation]: 'Scottish: lo{ch}',
  },
  {
    [ColumnName.Name]: 'dāl',
    [ColumnName.ArabicName]: 'دَال',
    [ColumnName.Transliteration]: 'd',
    [ColumnName.Isolated]: 'د',
    [ColumnName.Initial]: 'د',
    [ColumnName.Medial]: 'ـد',
    [ColumnName.Final]: 'ـد',
    [ColumnName.Pronunciation]: '{d}ear',
  },
  {
    [ColumnName.Name]: 'dhāl',
    [ColumnName.ArabicName]: 'ذَال',
    [ColumnName.Transliteration]: `dh (also ḏ)`,
    [ColumnName.Isolated]: 'ذ',
    [ColumnName.Initial]: 'ذ',
    [ColumnName.Medial]: 'ـذ',
    [ColumnName.Final]: 'ـذ',
    [ColumnName.Pronunciation]: '{th}at',
  },
  {
    [ColumnName.Name]: 'rāʾ',
    [ColumnName.ArabicName]: 'رَاء',
    [ColumnName.Transliteration]: 'r',
    [ColumnName.Isolated]: 'ر',
    [ColumnName.Initial]: 'ر',
    [ColumnName.Medial]: 'ـر',
    [ColumnName.Final]: 'ـر',
    [ColumnName.Pronunciation]: 'Spanish: pe{rr}o',
  },
  {
    [ColumnName.Name]: 'zāy / zayn',
    [ColumnName.ArabicName]: 'زَاي',
    [ColumnName.Transliteration]: 'z',
    [ColumnName.Isolated]: 'ز',
    [ColumnName.Initial]: 'ز',
    [ColumnName.Medial]: 'ـز',
    [ColumnName.Final]: 'ـز',
    [ColumnName.Pronunciation]: '{z}ebra',
  },
  {
    [ColumnName.Name]: 'sīn',
    [ColumnName.ArabicName]: 'سِين',
    [ColumnName.Transliteration]: 's',
    [ColumnName.Isolated]: 'س',
    [ColumnName.Initial]: 'سـ',
    [ColumnName.Medial]: 'ـسـ',
    [ColumnName.Final]: 'ـس',
    [ColumnName.Pronunciation]: '{s}in',
  },
  {
    [ColumnName.Name]: 'shīn',
    [ColumnName.ArabicName]: 'شِين',
    [ColumnName.Transliteration]: `sh (also š)`,
    [ColumnName.Isolated]: 'ش',
    [ColumnName.Initial]: 'شـ',
    [ColumnName.Medial]: 'ـشـ',
    [ColumnName.Final]: 'ـش',
    [ColumnName.Pronunciation]: '{sh}in',
  },
  {
    [ColumnName.Name]: 'ṣād',
    [ColumnName.ArabicName]: 'صَاد',
    [ColumnName.Transliteration]: `ṣ (also ş)`,
    [ColumnName.Isolated]: 'ص',
    [ColumnName.Initial]: 'صـ',
    [ColumnName.Medial]: 'ـصـ',
    [ColumnName.Final]: 'ـص',
    [ColumnName.Pronunciation]: 'like "{s}auce" with throat constricted',
  },
  {
    [ColumnName.Name]: 'ḍād',
    [ColumnName.ArabicName]: 'ضَاد',
    [ColumnName.Transliteration]: `ḍ (also ḑ)`,
    [ColumnName.Isolated]: 'ض',
    [ColumnName.Initial]: 'ضـ',
    [ColumnName.Medial]: 'ـضـ',
    [ColumnName.Final]: 'ـض',
    [ColumnName.Pronunciation]: 'like "{d}awn" with throat constricted',
  },
  {
    [ColumnName.Name]: 'ṭāʾ',
    [ColumnName.ArabicName]: 'طَاء',
    [ColumnName.Transliteration]: `ṭ (also ţ)`,
    [ColumnName.Isolated]: 'ط',
    [ColumnName.Initial]: 'طـ',
    [ColumnName.Medial]: 'ـطـ',
    [ColumnName.Final]: 'ـط',
    [ColumnName.Pronunciation]: 'like "s{t}all" with throat constricted',
  },
  {
    [ColumnName.Name]: 'ẓāʾ',
    [ColumnName.ArabicName]: 'ظَاء',
    [ColumnName.Transliteration]: `ẓ (also z̧)`,
    [ColumnName.Isolated]: 'ظ',
    [ColumnName.Initial]: 'ظـ',
    [ColumnName.Medial]: 'ـظـ',
    [ColumnName.Final]: 'ـظ',
    [ColumnName.Pronunciation]: 'like "fa{th}er" with throat constricted',
  },
  {
    [ColumnName.Name]: 'ʿayn',
    [ColumnName.ArabicName]: 'عَيْن',
    [ColumnName.Transliteration]: 'ʿ',
    [ColumnName.Isolated]: 'ع',
    [ColumnName.Initial]: 'عـ',
    [ColumnName.Medial]: 'ـعـ',
    [ColumnName.Final]: 'ـع',
    [ColumnName.Pronunciation]: 'guttural h like "{h}eart"',
  },
  {
    [ColumnName.Name]: 'ghayn',
    [ColumnName.ArabicName]: 'غَيْن',
    [ColumnName.Transliteration]: `gh (also ġ, ḡ)`,
    [ColumnName.Isolated]: 'غ',
    [ColumnName.Initial]: 'غـ',
    [ColumnName.Medial]: 'ـغـ',
    [ColumnName.Final]: 'ـغ',
    [ColumnName.Pronunciation]: 'Spanish: hi{g}o',
  },
  {
    [ColumnName.Name]: 'fāʾ',
    [ColumnName.ArabicName]: 'فَاء',
    [ColumnName.Transliteration]: 'f',
    [ColumnName.Isolated]: 'ف',
    [ColumnName.Initial]: 'فـ',
    [ColumnName.Medial]: 'ـفـ',
    [ColumnName.Final]: 'ـف',
    [ColumnName.Pronunciation]: '{f}ar',
  },
  {
    [ColumnName.Name]: 'qāf',
    [ColumnName.ArabicName]: 'قَاف',
    [ColumnName.Transliteration]: 'q',
    [ColumnName.Isolated]: 'ق',
    [ColumnName.Initial]: 'قـ',
    [ColumnName.Medial]: 'ـقـ',
    [ColumnName.Final]: 'ـق',
    [ColumnName.Pronunciation]: 'like "{c}aught" pronounced in back of mouth.',
  },
  {
    [ColumnName.Name]: 'kāf',
    [ColumnName.ArabicName]: 'كَاف',
    [ColumnName.Transliteration]: 'k',
    [ColumnName.Isolated]: 'ك',
    [ColumnName.Initial]: 'كـ',
    [ColumnName.Medial]: 'ـكـ	',
    [ColumnName.Final]: 'ـك',
    [ColumnName.Pronunciation]: '{c}ap',
  },
  {
    [ColumnName.Name]: 'lām',
    [ColumnName.ArabicName]: 'لاَم',
    [ColumnName.Transliteration]: 'l',
    [ColumnName.Isolated]: 'ل',
    [ColumnName.Initial]: 'لـ',
    [ColumnName.Medial]: 'ـلـ',
    [ColumnName.Final]: 'ـل',
    [ColumnName.Pronunciation]: '{l}amp',
  },
  {
    [ColumnName.Name]: 'mīm',
    [ColumnName.ArabicName]: 'مِيم',
    [ColumnName.Transliteration]: 'm',
    [ColumnName.Isolated]: 'م',
    [ColumnName.Initial]: 'مـ',
    [ColumnName.Medial]: 'ـمـ',
    [ColumnName.Final]: 'ـم',
    [ColumnName.Pronunciation]: '{m}e',
  },
  {
    [ColumnName.Name]: 'nūn',
    [ColumnName.ArabicName]: 'نُون',
    [ColumnName.Transliteration]: 'n',
    [ColumnName.Isolated]: 'ن',
    [ColumnName.Initial]: 'نـ',
    [ColumnName.Medial]: 'ـنـ',
    [ColumnName.Final]: 'ـن',
    [ColumnName.Pronunciation]: '{n}un',
  },
  {
    [ColumnName.Name]: 'hāʾ',
    [ColumnName.ArabicName]: 'هَاء',
    [ColumnName.Transliteration]: 'h',
    [ColumnName.Isolated]: 'ه',
    [ColumnName.Initial]: 'هـ',
    [ColumnName.Medial]: 'ـهـ',
    [ColumnName.Final]: 'ـه',
    [ColumnName.Pronunciation]: '{h}at',
  },
  {
    [ColumnName.Name]: 'wāw',
    [ColumnName.ArabicName]: 'وَاو',
    [ColumnName.Transliteration]: 'w / ū / ∅',
    [ColumnName.Isolated]: 'و',
    [ColumnName.Initial]: 'و',
    [ColumnName.Medial]: 'ـو',
    [ColumnName.Final]: 'ـو',
    [ColumnName.Pronunciation]: '{w}et, p{oo}l',
  },
  {
    [ColumnName.Name]: 'yāʾ',
    [ColumnName.ArabicName]: 'يَاء',
    [ColumnName.Transliteration]: 'y / ī',
    [ColumnName.Isolated]: 'ي',
    [ColumnName.Initial]: 'يـ',
    [ColumnName.Medial]: 'ـيـ',
    [ColumnName.Final]: 'ـي',
    [ColumnName.Pronunciation]: '{Y}oshi, m{ee}t',
  },
  {
    [ColumnName.Name]: 'hamzah',
    [ColumnName.ArabicName]: 'هَمْزة',
    [ColumnName.Transliteration]: 'ʾ',
    [ColumnName.Isolated]: 'ء',
    [ColumnName.Initial]: 'ء',
    [ColumnName.Medial]: 'ء',
    [ColumnName.Final]: 'ء',
    [ColumnName.Pronunciation]: 'glottal stop like "uh{-}oh"',
  },
  {
    [ColumnName.Name]: 'ʾalif hamzah',
    [ColumnName.ArabicName]: 'أَلِف هَمْزة',
    [ColumnName.Transliteration]: 'ʾ',
    [ColumnName.Isolated]: 'أ',
    [ColumnName.Initial]: 'إ',
    [ColumnName.Medial]: 'ـأ',
    [ColumnName.Final]: 'ـإ',
    [ColumnName.Pronunciation]: 'glottal stop like "uh{-}oh"',
  },
  {
    [ColumnName.Name]: 'wāw hamzah',
    [ColumnName.ArabicName]: 'وَاو هَمْزة',
    [ColumnName.Transliteration]: 'ʾ',
    [ColumnName.Isolated]: 'ؤ',
    [ColumnName.Initial]: 'ؤ',
    [ColumnName.Medial]: 'ـؤ',
    [ColumnName.Final]: 'ـؤ',
    [ColumnName.Pronunciation]: 'glottal stop like "uh{-}oh"',
  },
  {
    [ColumnName.Name]: 'yāʾ hamzah',
    [ColumnName.ArabicName]: 'يَاء هَمْزة',
    [ColumnName.Transliteration]: 'ʾ',
    [ColumnName.Isolated]: 'ئ',
    [ColumnName.Initial]: 'ئـ',
    [ColumnName.Medial]: 'ـئـ',
    [ColumnName.Final]: 'ـئ',
    [ColumnName.Pronunciation]: 'glottal stop like "uh{-}oh"',
  },
  {
    [ColumnName.Name]: 'ʾalif maddah',
    [ColumnName.ArabicName]: 'أَلِف مَدَّة',
    [ColumnName.Transliteration]: 'ʾā',
    [ColumnName.Isolated]: 'آ',
    [ColumnName.Initial]: 'آ',
    [ColumnName.Medial]: 'ـآ',
    [ColumnName.Final]: 'ـآ',
    [ColumnName.Pronunciation]: '',
  },
]
